- hosts: localhost
  become: yes
  vars:
    - user: 'pi'
    - dotfiles_repo: ''
    - ssh_key: '.ssh/id_rsa'
  tasks:
    - name: "Install system packages"
      apt:
        name: [bat, exa, fzf, tldr, vim, zsh]
        state: latest
